name: Send Text Message Manual

on: workflow_dispatch
jobs:
  data_refresh:
    name: send a message
    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      TARGET_PHONE_NUMBER: ${{ secrets.TARGET_PHONE_NUMBER }}
    runs-on: ubuntu-latest
    container:
     image: docker.io/richpauloo/tdox:prod.0.0.01
    steps:
      - name: (1) Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
      - name: (2) Download and plot
        run: |
          source('R/01_download_plot.R')
        shell: Rscript {0} 
      - name: (4) Commit changes
        run: bash ./R/run.sh 
      - name: (5) Send Text Message
        run: |
          source('R/02_message.R')
        shell: Rscript {0} 
      - name: (6) Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
