name: Send Text Message Manual

on: workflow_dispatch
jobs:
  data_refresh:
    name: send a message
    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      TARGET_PHONE_NUMBER: ${{ secrets.TARGET_PHONE_NUMBER }}
    runs-on: ubuntu-latest
    container:
     image: docker.io/richpauloo/tdox:prod.0.0.01
    steps:
      - name: (1) Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: (2) Download and plot
        run: |
          source('R/01_download_plot.R')
        shell: Rscript {0} 
      - name: GitHub Action for committing changes to a repository
        uses: devops-infra/action-commit-push@v0.9.2
      - name: (5) Send Text Message
        run: |
          source('R/02_message.R')
        shell: Rscript {0} 
      - name: (6) Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
