name: Send Text Message Scheduled

on:
  schedule:
    - cron:  '0 17 * * *'
jobs:
  data_refresh:
    name: send a message
    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      TARGET_PHONE_NUMBER: ${{ secrets.TARGET_PHONE_NUMBER }}
      TARGET_PHONE_NUMBER2: ${{ secrets.TARGET_PHONE_NUMBER2 }}
      TARGET_PHONE_NUMBER3: ${{ secrets.TARGET_PHONE_NUMBER3 }}
    runs-on: ubuntu-latest
    container:
     image: docker.io/richpauloo/tdox:prod.0.0.01
    steps:
      - name: (1) Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: (2) Download and plot
        run: |
          source('R/01_download_plot.R')
        shell: Rscript {0} 
      - name: (3) GitHub Action for committing changes to a repository
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-COMMIT] update daily plot"
      - name: (4) Send Text Message
        run: |
          source('R/02_message.R')
        shell: Rscript {0} 
      - name: (5) Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
